# Generated by Django 2.2.6 on 2020-03-16 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('description', models.CharField(blank=True, help_text='simple description text.', max_length=100, verbose_name='DESCRIPTION')),
                ('price', models.CharField(max_length=20, null=True, verbose_name='PRICE')),
                ('review', models.CharField(max_length=20, null=True, verbose_name='NUMBER_OF_REVIEWS')),
                ('score', models.CharField(max_length=20, null=True, verbose_name='SCORE')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ProductImages', verbose_name='IMAGE')),
                ('rank', models.CharField(blank=True, max_length=10, null=True, verbose_name='RANK')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'crawl_products',
                'ordering': ('-rank',),
            },
        ),
    ]
