# Generated by Django 2.2.6 on 2020-03-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_auto_20200319_1430'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='crawl_products',
        ),
    ]
