# Generated by Django 2.2.6 on 2020-03-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0005_auto_20200319_1523'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='crawl_products',
        ),
    ]
