# Generated by Django 2.2.6 on 2020-03-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0008_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
